import { Exercise, DayPlan } from '@/types/training';

const createExercise = (id: string, name: string, muscle: string, sets: number | string, reps: string, obs: string): Exercise => ({
  id, name, muscle, sets, reps, obs, gifUrl: undefined
});

export const ALL_AVAILABLE_EXERCISES: Exercise[] = [
  createExercise("p-01", "Supino Reto c/ Barra", "Peito", 4, "8-10", "Foco em carga"),
  createExercise("p-02", "Supino Inclinado Halter", "Peito", 3, "12", "Peito superior"),
  createExercise("p-03", "Crucifixo Máquina (Peck Deck)", "Peito", 3, "15", "Foco em isolamento"),
  createExercise("p-04", "Crossover Polia Alta", "Peito", 3, "12-15", "Foco em peito inferior"),
  createExercise("p-05", "Supino Reto c/ Halteres", "Peito", 4, "10", "Maior amplitude que a barra"),
  createExercise("p-06", "Flexão de Braços", "Peito", 3, "Falha", "Peso corporal"),
  createExercise("p-07", "Pull-over com Halter", "Peito", 3, "12", "Expansão torácica"),
  createExercise("c-01", "Puxada Frontal Aberta", "Costas", 4, "10-12", "Foco latíssimo"),
  createExercise("c-02", "Remada Curvada Pronada", "Costas", 3, "10", "Tronco inclinado"),
  createExercise("c-03", "Barra Fixa (Pull-up)", "Costas", 3, "Falha", "Peso corporal"),
  createExercise("c-04", "Levantamento Terra", "Costas", 3, "5-8", "Cadeia posterior e força"),
  createExercise("c-05", "Remada Unilateral (Serrote)", "Costas", 3, "10", "Grande amplitude"),
  createExercise("c-06", "Pull-Down na Polia", "Costas", 3, "15", "Braços esticados"),
  createExercise("o-01", "Desenvolvimento Militar", "Ombros", 3, "10", "Ombros estáveis"),
  createExercise("o-02", "Elevação Lateral", "Ombros", 4, "15", "Braços esticados"),
  createExercise("o-03", "Face Pull", "Ombros", 3, "15", "Deltoide posterior e postura"),
  createExercise("o-04", "Desenvolvimento Arnold", "Ombros", 3, "10", "Rotação de punho"),
  createExercise("o-05", "Elevação Lateral na Polia", "Ombros", 3, "12-15", "Tensão constante"),
  createExercise("b-01", "Rosca Direta Barra W", "Bíceps", 4, "10", "Sem balançar"),
  createExercise("b-02", "Rosca Martelo", "Bíceps", 3, "12", "Braquial e antebraço"),
  createExercise("t-01", "Tríceps Corda", "Tríceps", 3, "12-15", "Pico de contração"),
  createExercise("t-02", "Tríceps Testa", "Tríceps", 3, "10-12", "Cotovelos fechados"),
  createExercise("a-01", "Rosca Inversa Polia", "Antebraço", 3, "15", "Braquiorradial"),
  createExercise("l-01", "Agachamento Livre", "Pernas", 4, "8-10", "Amplitude máxima"),
  createExercise("l-02", "Leg Press 45º", "Pernas", 3, "12", "Pés largura ombro"),
  createExercise("l-03", "Cadeira Extensora", "Pernas", 4, "15", "Quadríceps"),
  createExercise("l-04", "Mesa Flexora", "Pernas", 4, "12", "Posteriores de coxa"),
  createExercise("l-05", "Stiff", "Pernas", 3, "10", "Posterior e glúteo"),
  createExercise("g-01", "Elevação Pélvica", "Glúteos", 4, "10-12", "Pico de contração"),
  createExercise("co-01", "Prancha Abdominal", "Core", 3, "1 min", "Core travado"),
  createExercise("co-02", "Abdominal Infra", "Core", 3, "15", "Controle a descida"),
  createExercise("cd-01", "Burpees", "Cardio", 3, "15", "Alta intensidade"),
  createExercise("cd-02", "Mountain Climbers", "Cardio", 3, "1 min", "Explosão"),
  createExercise("p-08", "Supino Declinado c/ Barra", "Peito", 3, "10-12", "Foco em peitoral inferior"),
  createExercise("p-09", "Crucifixo Inclinado c/ Halteres", "Peito", 3, "12", "Foco em alongamento superior"),
  createExercise("p-10", "Chest Press Máquina", "Peito", 4, "10-12", "Controle total do movimento"),
  createExercise("p-11", "Flexão Diamante", "Peito", 3, "Falha", "Foco em tríceps e miolo do peito"),
  createExercise("p-12", "Crossover Polia Baixa", "Peito", 3, "12-15", "Foco em peito superior"),
  createExercise("p-13", "Dips em Paralelas (Foco Peito)", "Peito", 3, "Falha", "Corpo inclinado à frente"),
  createExercise("c-07", "Remada Cavalinho", "Costas", 3, "10-12", "Foco em espessura"),
  createExercise("c-08", "Puxada Triângulo", "Costas", 3, "12", "Foco em latíssimo inferior"),
  createExercise("c-09", "Remada Curvada Supinada", "Costas", 3, "10", "Maior ativação de bíceps"),
  createExercise("c-10", "Puxada Articulada Unilateral", "Costas", 3, "12", "Correção de assimetria"),
  createExercise("c-11", "Lombar no Banco Romano", "Costas", 3, "15", "Fortalecimento eretores da espinha"),
  createExercise("c-12", "Barra Fixa Supinada (Chin-up)", "Costas", 3, "Falha", "Grande foco em bíceps"),
  createExercise("c-13", "Remada Pendlay", "Costas", 4, "8", "Explosividade saindo do chão"),
  createExercise("o-06", "Crucifixo Inverso c/ Halteres", "Ombros", 3, "15", "Deltoide posterior"),
  createExercise("o-07", "Remada Alta c/ Barra", "Ombros", 3, "12", "Foco em trapézio e lateral"),
  createExercise("o-08", "Elevação Frontal c/ Anilhas", "Ombros", 3, "12", "Deltoide anterior"),
  createExercise("o-09", "Encolhimento c/ Halteres", "Ombros", 4, "15", "Foco em trapézio superior"),
  createExercise("o-10", "Elevação Lateral Inclinado (Banco 45)", "Ombros", 3, "12", "Isolamento máximo lateral"),
  createExercise("o-11", "Z-Press (Sentado no chão)", "Ombros", 3, "10", "Estabilidade extrema de core"),
  createExercise("b-04", "Rosca 45 (Banco Inclinado)", "Bíceps", 3, "10", "Foco no alongamento da cabeça longa"),
  createExercise("b-05", "Rosca Concentrada", "Bíceps", 3, "12", "Pico de contração"),
  createExercise("b-06", "Rosca 21", "Bíceps", 3, "21", "7 curtas baixo, 7 alto, 7 completas"),
  createExercise("b-07", "Rosca Spider (Peito no banco)", "Bíceps", 3, "12", "Evita roubo com o corpo"),
  createExercise("t-03", "Tríceps Francês c/ Halter", "Tríceps", 3, "12", "Foco na porção longa"),
  createExercise("t-04", "Tríceps Pulley Barra Reta", "Tríceps", 3, "12", "Foco em carga"),
  createExercise("t-05", "Tríceps Coice na Polia", "Tríceps", 3, "15", "Pico de contração lateral"),
  createExercise("t-06", "Tríceps Supinado (Pegada Fechada)", "Tríceps", 3, "8-10", "Tríceps com carga alta"),
  createExercise("t-07", "Mergulho no Banco", "Tríceps", 3, "Falha", "Peso corporal ou com carga"),
  createExercise("a-02", "Flexão de Punho c/ Barra", "Antebraço", 3, "20", "Foco em flexores"),
  createExercise("a-03", "Extensão de Punho c/ Barra", "Antebraço", 3, "20", "Foco em extensores"),
  createExercise("a-04", "Rosca Zottman", "Antebraço", 3, "12", "Sobe supinada, desce pronada"),
  createExercise("l-06", "Agachamento Sumô", "Pernas", 3, "12-15", "Foco em adutores"),
  createExercise("l-07", "Hack Squat", "Pernas", 3, "10", "Isolamento de quadríceps"),
  createExercise("l-08", "Agachamento Búlgaro", "Pernas", 3, "10", "Unilateral - foco em glúteo e quadríceps"),
  createExercise("l-09", "Cadeira Flexora", "Pernas", 4, "12", "Isquiotibiais sentado"),
  createExercise("l-10", "Cadeira Adutora", "Pernas", 3, "15-20", "Parte interna da coxa"),
  createExercise("l-11", "Cadeira Abdutora", "Pernas", 3, "15-20", "Glúteo médio / lateral da coxa"),
  createExercise("l-12", "Passada / Afundo", "Pernas", 3, "20 passos", "Dinâmico e funcional"),
  createExercise("pt-01", "Panturrilha em Pé (Máquina)", "Panturrilha", 4, "15-20", "Máximo alongamento"),
  createExercise("pt-02", "Panturrilha Sentado (Cavalinho)", "Panturrilha", 4, "15", "Foco no sóleo"),
  createExercise("pt-03", "Panturrilha no Leg Press", "Panturrilha", 4, "15-20", "Pés paralelos"),
  createExercise("g-02", "Glúteo Coice no Cabo", "Glúteos", 3, "12-15", "Extensão de quadril"),
  createExercise("g-03", "Abdução de Quadril no Cabo", "Glúteos", 3, "15", "Foco em glúteo médio"),
  createExercise("g-04", "Frog Pumps", "Glúteos", 3, "30", "Ativação metabólica"),
  createExercise("co-03", "Abdominal Canivete", "Core", 3, "15", "Movimento simultâneo"),
  createExercise("co-04", "Prancha Lateral", "Core", 3, "45 seg", "Foco em oblíquos"),
  createExercise("co-05", "Russian Twist", "Core", 3, "30 seg", "Rotação de tronco"),
  createExercise("co-06", "Abdominal Roda", "Core", 3, "10-12", "Antiextensão de coluna"),
  createExercise("co-07", "Hanging Leg Raise (Na Barra)", "Core", 3, "12", "Foco em infra-abdômen"),
  createExercise("cd-03", "Kettlebell Swing", "Corpo Todo", 4, "15-20", "Explosão de quadril e cardio"),
  createExercise("cd-04", "Thrusters (Halteres)", "Corpo Todo", 3, "12", "Agachamento + Desenvolvimento"),
  createExercise("cd-05", "Polichinelos", "Cardio", 3, "1 min", "Aquecimento e resistência"),
  createExercise("cd-06", "Battle Rope (Corda Naval)", "Cardio", 4, "30 seg", "Alta intensidade para braços e core")
];
